<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Total.Recall</RootNamespace>
    <AssemblyName>Total.Recall</AssemblyName>
    <Version>2.4.0</Version>
    <AssemblyVersion>2.4.0.0</AssemblyVersion>
    <FileVersion>2.4.0.0</FileVersion>
    <InformationalVersion>2.4.0</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Total.Recall.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" Version="0.3.0-preview.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="System.Reflection.MetadataLoadContext" Version="8.0.1" />
  </ItemGroup>

</Project>
